window.skill = [
  {
    id: "Fire-Bolt",
    name: "Fire Bolt",
    icon: "img/skill/Fire Bolt.png",
    tags: ["Spell", "Projectile", "Fire", "AoE"],
    type: "Skill",
    description:
      "Launch a fire bolt that explodes on impact dealing additional damage in an area around the target.",
    stats: {
      skillLevel: 5,
      cost: "Aether 22",
      fireDamage: "3 - 6",
      projectileSpeed: 25,
      castSpeed: 1,
      requirements: "Rod",
    },
    effects: [
      "17% increased Burn Chance",
      "7% increased AoE Radius",
      "Gain +9% of Damage as Extra Fire Damage per 1 Skill Level",
    ],
	video: {
	  type: "mp4",
	  src: "img/skill/Fire-Bolt.mp4",
	},
    sort: 10,
  },
  {
    id: "Lightning-Quake",
    name: "Lightning Quake",
    icon: "img/skill/Lightning Quake.png",
    tags: ["AoE", "Melee", "Lightning"],
    type: "Skill",
    description:
      "Slam the ground with lightning and watch as enemies within the targeted area are damaged by periodic quakes.",
    stats: {
      skillLevel: 1,
      cost: "Aether 25",
      aoeRadius: 4.7,
      duration: 3,
      damageRate: 1,
      range: 15,
      requirements: "Level 10, 2h Mace or Staff",
    },
    effects: [
      "+50% of outgoing Physical Damage Converted to Lightning Damage",
      "20% decreased Attack Speed",
      "Gain +7% of Damage as Extra Lightning Damage per 1 Skill Level",
    ],
	video: {
	  type: "mp4",
	  src: "img/skill/Lightning-Quake.mp4",
	},
    sort: 20,
  },
  {
    id: "Ice-Shards",
    name: "Ice Shards",
    icon: "img/skill/Ice Shards.png",
    tags: ["Ranged", "Projectile", "Cold"],
    type: "Skill",
    description: "Blast a volley of ice shards from your rod.",
    stats: {
      skillLevel: 1,
      cost: "Aether 15",
      projectileSpeed: 25,
      requirements: "Level 10, Rod",
    },
    effects: [
      "+50% of outgoing Physical Damage Converted to Cold Damage",
      "+100% Projectile Pierce Chance",
      "Gain +8% of Damage as Extra Cold Damage per 1 Skill Level",
    ],
	video: {
	  type: "mp4",
	  src: "img/skill/Ice-Shards.mp4",
	},
    sort: 30,
  },
  {
    id: "Warp",
    name: "Warp",
    icon: "img/skill/Warp.png",
    tags: ["Teleport", "Cooldown", "Aether"],
    type: "Skill",
    description: "Teleport instantly to a targeted location.",
    stats: {
      skillLevel: 1,
      cost: "Aether 25",
      cooldown: 5,
      castSpeed: 1,
      range: 10,
      requirements: "Level 3",
    },
    effects: [
      "11% decreased Skill Cooldown",
      "1% decreased Skill Cooldown per 1 Skill Level",
    ],
	video: {
	  type: "mp4",
	  src: "img/skill/Warp.mp4",
	},
    sort: 40,
  },
  {
    id: "Aether-Rain",
    name: "Aether Rain",
    icon: "img/skill/Aether Rain.png",
    tags: ["Spell", "AoE", "Cooldown", "Aether"],
    type: "Skill",
    description:
      "Call down a destructive rain of Aether on enemies within a targeted area.",
    stats: {
      skillLevel: 1,
      cost: "Aether 25",
      cooldown: 4,
      aetherDamage: "3 - 5",
      aoeRadius: 3.6,
      duration: 2,
      damageRate: 1,
      castSpeed: 1,
      range: 15,
      requirements: "Level 3",
    },
    effects: [
      "10% increased AoE Radius",
      "8% increased Aether Damage per 1 Skill Level",
    ],
	video: {
	  type: "mp4",
	  src: "img/skill/Aether-Rain.mp4",
	},
    sort: 50,
  },
    {
    id: "Fervor",
    name: "Fervor",
    icon: "img/skill/Fervor.png",
    tags: ["Spell", "Aura", "AoE"],
    type: "Skill",
    description: "Increases aether regeneration while active.",
    stats: {
      skillLevel: 4,
      cost: "Aether 50",
      aoeRadius: 3.8,
      boostDuration: 4,
      impairmentDuration: 5,
      range: 500,
      itemLevel: 16,
      requirements: "Level 15",
    },
    effects: [
      "You and Allies gain Regenerate +2(-1-2)/s Aether per second",
      "You and Allies gain 5% increased Aether Regeneration per 1 Skill Level",
      "37% decreased Skill Resource Cost",
      "You and Allies gain 10% increased Loot Rarity",
    ],
    video: {
    },
    sort: 55,
  },
  
  {
    id: "Piercing-Shot",
    name: "Piercing Shot",
    icon: "img/skill/Piercing Shot.png",
    tags: ["Ranged", "Projectile", "Physical"],
    type: "Skill",
    description: "Fire a piercing shot from your ranged weapon.",
    stats: {
      skillLevel: 1,
      cost: "Aether 15",
      projectileSpeed: 25,
      requirements: "Rifle or Pistol",
    },
    effects: [
      "+120% Projectile Pierce Chance",
      "+25% Bleed Chance on Projectile Pierce",
      "Gain +10% of Damage as Extra Physical Damage per 1 Skill Level",
    ],
	video: {
	  type: "mp4",
	  src: "img/skill/Piercing-Shot.mp4",
	},
    sort: 60,
  },
  {
    id: "Rapid-Shot",
    name: "Rapid Shot",
    icon: "img/skill/Rapid Shot.png",
    tags: ["Ranged", "Projectile", "Cooldown", "Physical"],
    type: "Skill",
    description: "Fire multiple shots in rapid succession with your ranged weapon.",
    stats: {
      skillLevel: 1,
      cost: "Aether 25",
      cooldown: 4,
      projectileSpeed: 25,
      requirements: "Level 10, Rifle or Pistol",
    },
    effects: [
      "+3% Critical Hit Chance",
      "+2 to Maximum Skill Charges",
      "Gain +10% of Damage as Extra Physical Damage per 1 Skill Level",
    ],
	video: {
	  type: "mp4",
	  src: "img/skill/Rapid-Shot.mp4",
	},
    sort: 70,
  },
  {
    id: "Dash",
    name: "Dash",
    icon: "img/skill/Dash.png",
    tags: ["Spell", "Teleport", "Cooldown"],
    type: "Skill",
    description: "Quickly dash forward towards a target location.",
    stats: {
      skillLevel: 1,
      cost: "Aether 25",
      cooldown: 3.2,
      charges: 2,
      castSpeed: 2,
      range: 8,
      requirements: "Level 3",
    },
    effects: [
      "+1 to Maximum Skill Charges",
      "+1 to Maximum Skill Charges per 10 Skill Level",
    ],
	video: {
	  type: "mp4",
	  src: "img/skill/Dash.mp4",
	},
    sort: 80,
  },
  {
    id: "Bullet-Rain",
    name: "Bullet Rain",
    icon: "img/skill/Bullet Rain.png",
    tags: ["Ranged", "AoE", "Cooldown", "Physical"],
    type: "Skill",
    description:
      "Fire a massive volley of bullets that land in a targeted area.",
    stats: {
      skillLevel: 1,
      cost: "Aether 25",
      cooldown: 4,
      aoeRadius: 3.7,
      duration: 2,
      requirements: "Level 3, Pistol",
    },
    effects: [
      "15% increased AoE Radius",
      "Gain +10% of Damage as Extra Physical Damage per 1 Skill Level",
    ],
	video: {
	  type: "mp4",
	  src: "img/skill/Bullet-Rain.mp4",
	},
    sort: 90,
  },
  {
    id: "Aether-Walk",
    name: "Aether Walk",
    icon: "img/skill/Aether Walk.png",
    tags: ["Duration", "Cooldown", "Movement", "Aether"],
    type: "Skill",
    description:
      "Shift into the aether gaining phasing and increased movement speed for a short duration. Performing a melee attack while under the effect of Aether Walk causes an explosion of aether to occur. Performing any action or using any skill removes the effect of Aether Walk.",
    stats: {
      skillLevel: 1,
      cost: "Aether 25",
      cooldown: 7.9,
      aetherDamage: "6 - 10",
      castSpeed: 1,
      requirements: "Level 10",
    },
    effects: [
      "You gain 14% increased Movement Speed",
      "You gain 1% increased Movement Speed per 1 Skill Level",
      "Gain +9% of Damage as Extra Aether Damage per 1 Skill Level",
    ],
	video: {
	  type: "mp4",
	  src: "img/skill/Aether-Walk.mp4",
	},
    sort: 100,
  },
  {
    id: "Jolt",
    name: "Jolt",
    icon: "img/skill/Jolt.png",
    tags: ["Ranged", "Physical"],
    type: "Skill",
    description: "Unleash a powerful blast with your shotgun.",
    stats: {
      skillLevel: 1,
      cost: "Aether 20",
      range: 10,
      requirements: "Level 3, Shotgun",
    },
    effects: [
      "+36% Knockback Chance",
      "15% increased Attack Speed",
      "Gain +7% of Damage as Extra Physical Damage per 1 Skill Level",
    ],
	video: {
	  type: "mp4",
	  src: "img/skill/Jolt.mp4",
	},
    sort: 110,
  },
  {
    id: "Flash-Bang",
    name: "Flash Bang",
    icon: "img/skill/Flash Bang.png",
    tags: ["Spell", "AoE", "Cooldown", "Aether"],
    type: "Skill",
    description: "Throw dazzling flash grenades in all directions.",
    stats: {
      skillLevel: 1,
      cost: "Aether 25",
      cooldown: 10,
      aetherDamage: "6 - 10",
      aoeRadius: 4.6,
      boostDuration: 5,
      impairmentDuration: 5,
      castSpeed: 5,
      range: 500,
      requirements: "Level 10",
    },
    effects: [
      "+44% Knockback Chance",
      "48% increased Dazzle Chance",
      "Gain +18% of Damage as Extra Aether Damage per 1 Skill Level",
    ],
	video: {
	  type: "mp4",
	  src: "img/skill/Flash-Bang.mp4",
	},
    sort: 120,
  },
  {
    id: "Whirlwind",
    name: "Whirlwind",
    icon: "img/skill/Whirlwind.png",
    tags: ["Melee", "Movement", "Channeling", "Physical"],
    type: "Skill",
    description:
      "Spin while armed with melee weapons, striking everything in your path.",
    stats: {
      skillLevel: 1,
      cost: "Aether 15",
      cooldown: 1,
      damageRate: 5,
      range: 500,
      requirements: "Level 10, Melee",
    },
    effects: [
      "You gain 25% decreased Movement Speed",
      "You gain 1% increased Movement Speed per 1 Skill Level",
    ],
	video: {
	  type: "mp4",
	  src: "img/skill/Whirlwind.mp4",
	},
    sort: 130,
  },
  {
    id: "Flame-Strike",
    name: "Flame Strike",
    icon: "img/skill/Flame Strike.png",
    tags: ["Melee", "Fire"],
    type: "Skill",
    description: "Strike a fiery blow with your two-handed melee weapon.",
    stats: {
      skillLevel: 1,
      cost: "Aether 15",
      requirements: "Level 3, Melee, Two Handed Weapon",
    },
    effects: [
      "+50% of outgoing Physical Damage Converted to Fire Damage",
      "17% increased Attack Speed",
      "Gain +10% of Damage as Extra Fire Damage per 1 Skill Level",
    ],
	video: {
	  type: "mp4",
	  src: "img/skill/Flame-Strike.mp4",
	},
    sort: 140,
  },
  {
    id: "Double-Slice",
    name: "Double Slice",
    icon: "img/skill/Double Slice.png",
    tags: ["Melee", "Single target", "Physical"],
    type: "Skill",
    description: "Perform two fast strikes with your one-handed melee weapon.",
    stats: {
      skillLevel: 1,
      cost: "Aether 15",
      requirements: "Melee, One Handed Weapon",
    },
    effects: [
      "10% increased Critical Hit Damage",
      "4% increased Attack Speed per 1 Skill Level",
    ],
	video: {
	  type: "mp4",
	  src: "img/skill/Double-Slice.mp4",
	},
    sort: 150,
  },
  {
    id: "Shield-Bash",
    name: "Shield Bash",
    icon: "img/skill/Shield Bash.png",
    tags: ["Melee", "Shield", "Movement", "AoE", "Physical"],
    type: "Skill",
    description:
      "Charge at your enemy, bashing the target and dealing damage in a cone that extends beyond the target.",
    stats: {
      skillLevel: 1,
      cost: "Aether 25",
      physicalDamage: "6 - 10",
      castSpeed: 1,
      range: 5,
      requirements: "Level 3, Shield",
    },
    effects: [
      "+17% Stun Chance",
      "You gain 23% increased Movement Speed",
      "Gain +7% of Damage as Extra Physical Damage per 20 Shield Defense",
    ],
	video: {
	  type: "mp4",
	  src: "img/skill/Shield-Bash.mp4",
	},
    sort: 160,
  },
  {
    id: "Sweep",
    name: "Sweep",
    icon: "img/skill/Sweep.png",
    tags: ["AoE", "Melee", "Physical"],
    type: "Skill",
    description:
      "Perform a circular attack, knocking back and damaging enemies around you.",
    stats: {
      skillLevel: 6,
      cost: "Aether 35",
      aoeRadius: 3,
      damageRate: 1,
      range: 15,
      requirements: "Level 3, 2h Mace or Staff",
    },
    effects: [
      "+100% Knockback Chance",
      "Gain +9% of Damage as Extra Physical Damage per 1 Skill Level",
    ],
	video: {
	  type: "mp4",
	  src: "img/skill/Sweep.mp4",
	},
    sort: 170,
  },
  {
    id: "Leap-Attack",
    name: "Leap Attack",
    icon: "img/skill/Leap Attack.png",
    tags: ["Melee", "AoE", "Physical"],
    type: "Skill",
    description:
      "Leap towards a target location and deal damage to surrounding enemies where you land.",
    stats: {
      skillLevel: 1,
      cost: "Aether 25",
      aoeRadius: 2.9,
      castSpeed: 2,
      range: 15,
      requirements: "Level 3, Melee",
    },
    effects: ["+16% Stun Chance", "2% increased AoE Radius per 1 Skill Level"],
	video: {
	  type: "mp4",
	  src: "img/skill/Leap-Attack.mp4",
	},
    sort: 180,
  },
  {
    id: "War-Cry",
    name: "War Cry",
    icon: "img/skill/War Cry.png",
    tags: ["Spell", "Shout", "AoE", "Cooldown", "Duration", "Physical"],
    type: "Skill",
    description:
      "Sound a mighty war cry that causes affected enemies to do less damage and take more damage.",
    stats: {
      skillLevel: 1,
      cost: "Aether 25",
      cooldown: 8,
      physicalDamage: "6 - 10",
      aoeRadius: 3.6,
      boostDuration: 5,
      impairmentDuration: 5,
      castSpeed: 1,
      range: 500,
      requirements: "Level 10",
    },
    effects: [
      "You and Allies gain 6% increased Damage on Skill Activation",
      "Enemies gain 6% decreased Damage on Skill Activation",
      "3% increased AoE Radius per 1 Skill Level",
    ],
	video: {
	  type: "mp4",
	  src: "img/skill/War-Cry.mp4",
	},
    sort: 190,
  },
  {
    id: "Shield-Rush",
    name: "Shield Rush",
    icon: "img/skill/Shield Rush.png",
    tags: ["Melee", "Shield", "Movement", "Channeling", "Physical"],
    type: "Skill",
    description:
      "Charge through crowds of enemies, dealing damage with your shield and leaving destruction in your wake.",
    stats: {
      skillLevel: 1,
      cost: "Aether 20",
      physicalDamage: "6 - 10",
      damageRate: 5,
      castSpeed: 1,
      range: 500,
      requirements: "Level 10, Shield",
    },
    effects: [
      "+15% Stun Chance",
      "You gain 23% increased Movement Speed",
      "Gain +9% of Damage as Extra Physical Damage per 1 Skill Level",
    ],
	video: {
	  type: "mp4",
	  src: "img/skill/Shield-Rush.mp4",
	},
    sort: 200,
  },
  {
    id: "Vigor",
    name: "Vigor",
    icon: "img/skill/Vigor.png",
    tags: ["Spell", "Aura", "AoE"],
    type: "Skill",
    description: "Increases life regeneration while active.",
    stats: {
      skillLevel: 4,
      cost: "Aether 50",
      aoeRadius: 3.4,
      boostDuration: 5,
      impairmentDuration: 5,
      range: 500,
      requirements: "Level 15",
    },
    effects: [
      "You and Allies gain Regenerate +3/s Life per second",
      "You and Allies gain 5% increased Life Regeneration per 1 Skill Level",
      "You and Allies gain Regenerate +4/s Life per second",
      "You and Allies gain 9% increased Damage against Enemies on Full Life",
    ],
    video: {
    },
    sort: 220,
  },
  
  {
  id: "Disintegrate",
  name: "Disintegrate",
  icon: "img/skill/Disintegrate.png",
  tags: ["Spell", "Aether", "Channeling", "Beam", "DoT"],
  type: "Skill",
  description: "Channel an aether beam that builds up damage over time and explodes slain enemies.",
  stats: {
    skillLevel: 1,
    cost: "Aether 15",
    aetherDamage: "9 - 15",
    castSpeed: 1,
    range: 15,
    requirements: "Level 18, Rod or Staff"
  },
  effects: [
    "Adds 1 to 2 Aether Damage per 20 Intelligence",
    "8% increased Aether Damage per 1 Skill Level"
  ],
  video: {},
  sort: 230
},

{
  id: "Lightning-Bolt",
  name: "Lightning Bolt",
  icon: "img/skill/Lightning Bolt.png",
  tags: ["Ranged", "Projectile", "Lightning"],
  type: "Skill",
  description: "Discharge a bolt of lightning that chains to additional targets.",
  stats: {
    skillLevel: 1,
    cost: "Aether 15",
    projectileSpeed: 25,
    requirements: "Level 18, Rifle or Pistol"
  },
  effects: [
    "+50% Physical Damage converted to Lightning",
    "+166% Chain Chance",
    "+8% Extra Lightning Damage per level"
  ],
  video: {},
  sort: 240
},

{
  id: "Pyro-Bullet",
  name: "Pyro Bullet",
  icon: "img/skill/Pyro Bullet.png",
  tags: ["Ranged", "Projectile", "Fire"],
  type: "Skill",
  description: "Fire enhanced bullets that ignite enemies.",
  stats: {
    skillLevel: 1,
    cost: "Aether 15",
    projectileSpeed: 25,
    requirements: "Level 18, Rifle or Pistol"
  },
  effects: [
    "+50% Physical Damage converted to Fire",
    "Increased Burn Chance",
    "+6% Extra Fire Damage per level"
  ],
  video: {},
  sort: 250
},

{
  id: "Recoil",
  name: "Recoil",
  icon: "img/skill/Recoil.png",
  tags: ["Ranged", "Projectile", "Movement", "Physical"],
  type: "Skill",
  description: "Slide back while firing your weapon.",
  stats: {
    skillLevel: 1,
    cost: "Aether 25",
    projectileSpeed: 25,
    requirements: "Level 10, Rifle or Pistol or Shotgun"
  },
  effects: [
    "Chance to deal Double or Triple Damage",
    "+20% Extra Physical Damage per level"
  ],
  video: {},
  sort: 260
},

{
  id: "Trip-Mine",
  name: "Trip Mine",
  icon: "img/skill/Trip Mine.png",
  tags: ["Mine", "AoE", "Physical"],
  type: "Skill",
  description: "Place a mine that explodes when triggered.",
  stats: {
    skillLevel: 1,
    cost: "Aether 25",
    physicalDamage: "6 - 10",
    aoeRadius: 2.6,
    castSpeed: 1.5,
    range: 15,
    requirements: "Level 18"
  },
  effects: [
    "+45% Knockback Chance",
    "+18% Extra Physical Damage per level",
    "+2 to Maximum Mines"
  ],
  video: {},
  sort: 270
}
];
